### PR TITLE
fix: Throw for non-numeric `vwidth` or `vheight` values

### LINKED ISSUE #74: webshot2 incompatibility with bookdown for PDF output
I have a bookdown project that suddenly gave me errors when compiling to PDF. It took me a while to go down the long list or errors to spot that `webshot2` was in the list. `webshot2` is not used or necessary for this book (it was installed for another.) Uninstalling webshot2 the error no longer appears. 
The error is specific to sizing images or plots with a command within the `{r}` segment, *e.g.*: `out.width = if (knitr:::is_html_output()) '70%' else '90%'`. The error is given as:

```
Error in `initialize()`:
! `width` must be a whole number, not the string "90%".
```

Indeed if I change `90%` to `90` the error passed onto the next chunk with a similar option.

I am opening this issue FYI. Here is the long list of the errors:

```
Error in `initialize()`:
! `width` must be a whole number, not the string "90%".
Backtrace:
     x
  1. \-bookdown::render_book("index.Rmd", "bookdown::pdf_book")
  2.   \-bookdown:::render_cur_session(...)
  3.     \-rmarkdown::render(main, output_format, ..., clean = clean, envir = envir)
  4.       \-knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5.         \-knitr:::process_file(text, output)
  6.           +-xfun:::handle_error(...)
  7.           +-base::withCallingHandlers(...)
  8.           \-knitr:::process_group(group)
  9.             \-knitr:::call_block(x)
 10.               \-knitr:::block_exec(params)
 11.                 \-knitr:::eng_r(options)
 12.                   +-knitr:::in_input_dir(...)
 13.                   | \-knitr:::in_dir(input_dir(), expr)
 14.                   \-knitr (local) evaluate(...)
 15.                     \-evaluate::evaluate(...)
 16.                       +-base::withRestarts(...)
 17.                       | \-base (local) withRestartList(expr, restarts)
 18.                       |   +-base (local) withOneRestart(withRestartList(expr, restarts[-nr]), restarts[[nr]])
 19.                       |   | \-base (local) doWithOneRestart(return(expr), restart)
 20.                       |   \-base (local) withRestartList(expr, restarts[-nr])
 21.                       |     \-base (local) withOneRestart(expr, restarts[[1L]])
 22.                       |       \-base (local) doWithOneRestart(return(expr), restart)
 23.                       +-evaluate:::with_handlers(...)
 24.                       | +-base::eval(call)
 25.                       | | \-base::eval(call)
 26.                       | \-base::withCallingHandlers(...)
 27.                       \-watcher$print_value(ev$value, ev$visible, envir)
 28.                         +-base::withVisible(handle_value(handler, value, visible, envir))
 29.                         \-evaluate:::handle_value(handler, value, visible, envir)
 30.                           \-handler$value(value, visible)
 31.                             \-knitr (local) fun(x, options = options)
 32.                               +-base::withVisible(knit_print(x, ...))
 33.                               \-knitr::knit_print(x, ...)
 34.                                 \-knitr:::html_screenshot(x)
 35.                                   +-knitr:::in_dir(...)
 36.                                   +-base::do.call(...)
 37.                                   \-webshot2 (local) `<fn>`(...)
 38.                                     \-base::lapply(...)
 39.                                       \-webshot2 (local) FUN(X[[i]], ...)
 40.                                         \-webshot2:::new_session_screenshot(...)
 41.                                           \-chromote$new_session(wait_ = FALSE, width = vwidth, height = vheight)
 42.                                             \-chromote:::create_session(...)
 43.                                               \-ChromoteSession$new(...)
 44.                                                 \-chromote (local) initialize(width = 992)
 45.                                                   \-chromote:::check_number_whole(width)
 46.                                                     \-chromote:::.stop_not_number(...)
 47.                                                       \-chromote:::stop_input_type(...)
 48.                                                         \-rlang::abort(message, ..., call = call, arg = arg)

Quitting from book.Rmd:510-527 [flowofinformation]
```

Removing `webshot2` fixed the issue for this book.

JYS

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #74 

``` r
pkgload::load_all()
#> ℹ Loading webshot2

webshot2::webshot("https://posit.co", vwidth = "90%")
#> Error in as_rounded_int(vwidth): `vwidth` must be an integer number of pixels, not '90%'.
```

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -1,4 +1,8 @@
 as_rounded_int <- function(x) {
+  x_name <- deparse(substitute(x))
+  if (!is.numeric(x)) {
+    stop("`", x_name, "` must be an integer number of pixels, not '", x, "'.")
+  }
```
Comment (wch) [inline R/utils.R]:
```suggestion
  if (!is.numeric(x)) {
    x_name <- deparse(substitute(x))
    stop("`", x_name, "` must be a number representing the number of pixels, not '", x, "'.")
  }
```

Better to do the `substitute` stuff only when needed. Also, the input doesn't have to be an integer (the purpose of this function is to turn numbers into integers).

Comment (gadenbuie) [reply R/utils.R]: I could move the check into `webshot2` but the point is that users should be providing integers for `vwidth` and `vheight`.

Comment (gadenbuie) [reply R/utils.R]:
```suggestion
  if (!is.numeric(x)) {
    x_name <- deparse(substitute(x))
    stop("`", x_name, "` must be an integer number of pixels, not '", x, "'.")
  }
```

Comment (gadenbuie) [reply R/utils.R]: I could also rename this function now that it's more specific than just rounding integers

**Review by wch — APPROVED** [review]

**Comment by wch** [comment]
Looks good!
