### PR TITLE
fix: Set device width and height before screenshot

### LINKED ISSUE #197: GT_Save Issues using VWidth and VHeight
Hello! 

I updated chromote to 0.4.0 since I was running into issues with GT_Save now that it no longer supports old headless mode.

However, after I ran the update, the functions vwidth and vheight no longer work. Is this related to the update at all with chromote?

Below is a quick example:

```r
NFLplayer_table%>%
  gt()%>%
  gt_theme_538_TB()%>%
  cols_label(headshots = "", player_display_name = "Kicker", team_logo_espn = "",
             Attempted_Field_Goals = "Field Goals Att", Avg_FP = "Fantasy Points", Avg_xFP = "Exp. Fantasy Points", FPOE = "FPs Over Expected",
             Made_Field_Goals = "Field Goals Made", FGOP = "FGs Over Expected",
             FG_Perc = "Field Goal Perc. (%)", FG_Perc_Over_Expected = "FG % Over Expected")%>%
  cols_align(align = "center")%>%
  tab_source_note(source_note = md("Table: **@FF_MarvinE** | Source: **@nflfastR**"))%>%
  tab_header(title = md("**Kicker Fantasy Points & Field Goal Efficiency Metrics**"), 
             subtitle = "2024 | Efficiency Metrics based on Field Goal Probability (excludes blocked kicks) | Min. 3 Field Goal Attempts")%>%
  gtExtras::gt_img_rows(team_logo_espn, height = 40)%>%
  gtExtras::gt_img_rows(headshots, height = 40)%>%
  data_color(columns = c(FPOE), colors = scales::col_numeric(palette = c("PuBuGn"),domain = NULL))%>%
  data_color(columns = c(FGOP), colors = scales::col_numeric(palette = c("PuBuGn"),domain = NULL))%>%
  data_color(columns = c(FG_Perc_Over_Expected), colors = scales::col_numeric(palette = c("PuBuGn"),domain = NULL))%>%
  tab_spanner(
    label = "Per Game",
    columns = c(
      Avg_xFP, Avg_FP, FPOE))%>%
  tab_spanner(
    label = "Field Goal Efficiency",
    columns = c(
      Attempted_Field_Goals,Made_Field_Goals, FGOP, FG_Perc, FG_Perc_Over_Expected))%>%
  gtsave("2024_Kicker_Eff_Week11.png", path = "Documents/Fantasy Football Charts/2025 Off-Season/",
         vwidth = 2000, vheight = 800)

```

### PR DESCRIPTION
**Pull request by gadenbuie**
We've noticed, e.g. in rstudio/chromote#197, that for Chrome's new headless mode (v132+), `ChromoteSession$new()` and `ChromoteSession$new_session()` with `width` and `height` don't actually set the viewport width and height.

This PR works around that limitation by calling `Emulation$setDeviceMetricsOverride()` before taking the screenshot.

Fixes rstudio/chromote#197

### CODE REVIEW

File: R/webshot.R [hunk 1]
```diff
@@ -308,7 +329,7 @@ new_session_screenshot <- function(
     })$
     finally(function() {
       # Close down the session if we successfully started one
-      if (!is.null(s)) s$close()
+      # if (!is.null(s)) s$close()
```
Comment (wch) [inline R/webshot.R]: Just wondering, why is this commented out?

**Review by wch — APPROVED** [review]

File: R/webshot.R (hunk 1 above)
Comment (gadenbuie) [reply R/webshot.R]: Thanks for spotting this! I need to restore the line. During debug I took this line out so I could access the screenshot session to see what was going on

Comment (gadenbuie) [inline R/webshot.R]:
```suggestion
      if (!is.null(s)) s$close()
```
